#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0pre on Fri Jan  7 13:57:44 2022 from "C:\Users\cnerwan\Desktop\TR test data logger\TR_test_data_logger.wxg"
#

import wx

# begin wxGlade: dependencies
import wx.grid
# end wxGlade

# begin wxGlade: extracode
import csv
import os
import time
from time import sleep
import modbus_tk.defines as cst
import numpy as np
import serial
import serial.tools.list_ports
import wx
import wx.grid
import wx.xrc
from modbus_tk import modbus_rtu
# end wxGlade
from modbus_tk.exceptions import ModbusInvalidResponseError


class MyFrame(wx.Frame):
    def \
            __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        global master
        global slave_addr
        global ser
        global time_cycle
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetTitle("Safe Digital Test Tool")

        self.frame_statusbar = self.CreateStatusBar(1)
        self.frame_statusbar.SetStatusWidths([-1])
        # statusbar fields
        frame_statusbar_fields = ["frame_statusbar"]
        for i in range(len(frame_statusbar_fields)):
            self.frame_statusbar.SetStatusText(frame_statusbar_fields[i], i)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "MDC4-M Temperature Test Data Logger V1.0")
        sizer_1.Add(label_2, 0, wx.ALL, 3)

        self.notebook_1 = wx.Notebook(self.panel_1, wx.ID_ANY)
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)

        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "TR test")

        sizer_2 = wx.BoxSizer(wx.VERTICAL)

        sizer_3 = wx.StaticBoxSizer(wx.StaticBox(self.notebook_1_pane_1, wx.ID_ANY, "COM"), wx.HORIZONTAL)
        sizer_2.Add(sizer_3, 0, wx.EXPAND, 0)

        self.choice_1 = wx.Choice(self.notebook_1_pane_1, wx.ID_ANY, choices=["choice 1"])
        self.choice_1.SetMinSize(wx.DLG_UNIT(self.choice_1, wx.Size(100, 12)))
        self.choice_1.SetSelection(0)
        sizer_3.Add(self.choice_1, 0, wx.ALL, 3)

        self.button_1 = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, "Start")
        sizer_3.Add(self.button_1, 0, wx.ALL, 3)

        self.button_2 = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, "Stop")
        self.button_2.Enable(False)
        sizer_3.Add(self.button_2, 0, wx.ALL, 3)

        sizer_4 = wx.StaticBoxSizer(wx.StaticBox(self.notebook_1_pane_1, wx.ID_ANY, "Modbus Address"), wx.HORIZONTAL)
        sizer_2.Add(sizer_4, 0, wx.EXPAND, 0)

        self.text_ctrl_1 = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "1")
        self.text_ctrl_1.SetMinSize(wx.DLG_UNIT(self.text_ctrl_1, wx.Size(100, 12)))
        sizer_4.Add(self.text_ctrl_1, 0, wx.ALL, 3)

        sizer_5 = wx.StaticBoxSizer(wx.StaticBox(self.notebook_1_pane_1, wx.ID_ANY, "Read Cycle (s)"), wx.HORIZONTAL)
        sizer_2.Add(sizer_5, 0, wx.EXPAND, 0)

        self.spin_ctrl_1 = wx.SpinCtrl(self.notebook_1_pane_1, wx.ID_ANY, "10", min=1, max=600)
        self.spin_ctrl_1.SetMinSize(wx.DLG_UNIT(self.spin_ctrl_1, wx.Size(100, 12)))
        sizer_5.Add(self.spin_ctrl_1, 0, wx.ALL, 3)

        sizer_6 = wx.StaticBoxSizer(wx.StaticBox(self.notebook_1_pane_1, wx.ID_ANY, "Data directory"), wx.VERTICAL)
        sizer_2.Add(sizer_6, 0, wx.EXPAND, 0)

        self.window_1 = wx.DirPickerCtrl(self.notebook_1_pane_1, wx.ID_ANY)
        self.window_1.SetMinSize(wx.DLG_UNIT(self.window_1, wx.Size(246, 12)))
        sizer_6.Add(self.window_1, 0, wx.EXPAND, 0)

        self.label_3 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, "The data file name is \"MDC4_M_TR_Data_yyyymmdd.csv\"")
        sizer_6.Add(self.label_3, 0, wx.ALL, 3)

        self.grid_2 = wx.grid.Grid(self.notebook_1_pane_1, wx.ID_ANY, size=(1, 1))
        self.grid_2.CreateGrid(1, 2)
        self.grid_2.SetRowLabelSize(100)
        self.grid_2.SetColLabelSize(33)
        self.grid_2.SetColLabelValue(0, u"Temp. (℃）")
        self.grid_2.SetColSize(0, 127)
        self.grid_2.SetColLabelValue(1, "Humidity (%)")
        self.grid_2.SetColSize(1, 127)
        self.grid_2.SetRowLabelValue(0, "Environment")
        self.grid_2.SetMinSize(wx.DLG_UNIT(self.grid_2, wx.Size(206, 30)))
        sizer_2.Add(self.grid_2, 0, wx.ALL | wx.EXPAND, 3)

        self.grid_1 = wx.grid.Grid(self.notebook_1_pane_1, wx.ID_ANY, size=(1, 1))
        self.grid_1.CreateGrid(6, 3)
        self.grid_1.SetRowLabelSize(96)
        self.grid_1.SetColLabelSize(43)
        self.grid_1.SetColLabelValue(0, u"Phase A (℃)")
        self.grid_1.SetColSize(0, 85)
        self.grid_1.SetColLabelValue(1, u"Phase B (℃)")
        self.grid_1.SetColSize(1, 85)
        self.grid_1.SetColLabelValue(2, u"Phase C (℃)")
        self.grid_1.SetColSize(2, 85)
        self.grid_1.SetMinSize(wx.DLG_UNIT(self.grid_1, wx.Size(206, 80)))
        sizer_2.Add(self.grid_1, 0, wx.ALL | wx.EXPAND, 3)

        self.grid_3 = wx.grid.Grid(self.notebook_1_pane_1, wx.ID_ANY, size=(1, 1))
        self.grid_3.CreateGrid(1, 4)
        self.grid_3.SetColLabelValue(0, u"Temp. (℃）")
        self.grid_3.SetColLabelValue(1, "P (bar)")
        self.grid_3.SetColLabelValue(2, "P20 (bar)")
        self.grid_3.SetColLabelValue(3, "P20_avg (bar)")
        self.grid_3.SetRowLabelValue(0, "Manometer")
        sizer_2.Add(self.grid_3, 1, wx.EXPAND, 0)

        self.notebook_1_pane_1.SetSizer(sizer_2)

        self.panel_1.SetSizer(sizer_1)

        sizer_1.Fit(self)
        self.Layout()

        self.timer_1 = wx.Timer()
        self.timer_1.SetOwner(self, wx.ID_ANY)
        self.__set_properties()
        self.Bind(wx.EVT_TIMER, self.do_logging, self.timer_1)

        self.Bind(wx.EVT_BUTTON, self.start_logging, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.stop_logging, self.button_2)
        # end wxGlade

    def __set_properties(self):
        global ser
        # serial port
        ser = serial.Serial()
        preferred_index = 0
        self.choice_1.Clear()
        self.ports = []
        for n, (portname, desc, hwid) in enumerate(sorted(serial.tools.list_ports.comports())):
            self.choice_1.Append(u'{} - {}'.format(portname, desc))
            self.ports.append(portname)
            if ser.name == portname:
                preferred_index = n
        self.choice_1.SetSelection(preferred_index)
        self.frame_statusbar.SetStatusText('Please select COM/Modbus Addr/Cycle/Folder and start...', 0)

    def show_message(self, msg='message'):
        dlg = wx.MessageDialog(None, msg, 'Information', wx.OK)
        if dlg.ShowModal() == wx.ID_OK:
            dlg.Close(True)
        else:
            dlg.Close(True)
        dlg.Destroy()

    def start_logging(self, event):  # wxGlade: MyFrame.<event_handler>
        global master
        global slave_addr
        global ser
        global time_cycle

        PORT = self.ports[self.choice_1.GetSelection()]
        slave_addr = int(self.text_ctrl_1.GetValue())

        ser = serial.Serial(port=PORT, baudrate=9600, bytesize=8, parity='N', stopbits=1, xonxoff=0)

        master = modbus_rtu.RtuMaster(ser)
        master.set_timeout(5.0)
        master.set_verbose(True)

        # self.button_1.Label = 'Connected'
        # self.button_1.SetBackgroundColour(wx.SystemSettings.GetColour(wx.SYS_COLOUR_HIGHLIGHT))
        self.button_1.Disable()
        self.button_2.Enable()

        time_cycle = self.spin_ctrl_1.GetValue() * 1000
        self.timer_1.Start(time_cycle)
        # self.label_4.SetLabelText("Status: Running...")
        self.frame_statusbar.SetStatusText('Running...', 0)

    def stop_logging(self, event):  # wxGlade: MyFrame.<event_handler>
        master.close()
        if ser.isOpen():
            ser.close()
        self.button_1.Label = 'Open'
        self.button_1.Enable()
        self.button_1.SetBackgroundColour(self.button_2.GetBackgroundColour())
        self.button_2.Disable()
        self.timer_1.Stop()
        # self.label_4.SetLabelText("Status: Stopped")
        self.frame_statusbar.SetStatusText('Stopped...', 0)

    def stop_timer(self):
        master.close()
        if ser.isOpen():
            ser.close()
        self.button_1.Label = 'Open'
        self.button_1.Enable()
        self.button_1.SetBackgroundColour(self.button_2.GetBackgroundColour())
        self.button_2.Disable()
        self.timer_1.Stop()
        # self.label_4.SetLabelText("Status: Stopped")
        # self.frame_statusbar.SetStatusText('Stopped...', 0)

    def do_logging(self, event):
        global time_cycle
        global master
        global ser
        global slave_addr

        try:
            localtime = time.localtime(time.time())
            date_string = "{:04d}{:02d}{:02d}".format(localtime.tm_year, localtime.tm_mon, localtime.tm_mday)
            file_name = "MDC4_M_TR_Data_{}.csv".format(date_string)
            data_folder = self.window_1.GetPath()
            if not os.path.exists(data_folder):
                os.mkdir(data_folder)
            data_file = "{}/{}".format(data_folder, file_name)
            # print(data_file)
            self.label_3.SetLabelText("The data file name is \"{}\"".format(file_name))

            var_names = ['Time', 'Env_T', 'Env_H',
                         'Unit1_A_T', 'Unit1_B_T', 'Unit1_C_T',
                         'Unit2_A_T', 'Unit2_B_T', 'Unit2_C_T',
                         'Unit3_A_T', 'Unit3_B_T', 'Unit3_C_T',
                         'Unit4_A_T', 'Unit4_B_T', 'Unit4_C_T',
                         'Unit5_A_T', 'Unit5_B_T', 'Unit5_C_T',
                         'Unit6_A_T', 'Unit6_B_T', 'Unit6_C_T',
                         'Unit1_Mano_T','Unit1_Mano_P','Unit1_Mano_P20','Unit1_Mano_P20_avg']
            var_default = ['2022-01-07 00:00:00'] + ['0' for i in range(24)]
            line_default = dict(zip(var_names, var_default))
            with open(data_file, 'a', newline='') as csvfile:
                writer = csv.DictWriter(csvfile, fieldnames=var_names)

                file_size = os.stat(data_file)
                if file_size.st_size == 0:
                    writer.writeheader()

                raw_env_data = np.array(master.execute(slave_addr, cst.READ_INPUT_REGISTERS, 21, 2))
                sleep(0.1)
                raw_t_data = np.array(master.execute(slave_addr, cst.READ_INPUT_REGISTERS, 0, 18))
                sleep(0.1)
                raw_mano_data = np.array(master.execute(slave_addr, cst.READ_INPUT_REGISTERS, 500, 4))
                sleep(0.1)

                self.grid_2.SetCellValue([0, 0], str(raw_env_data[0] * 0.1))  # env T
                self.grid_2.SetCellValue([0, 1], str(raw_env_data[1]))  # env H

                self.grid_3.SetCellValue([0, 0], str(raw_mano_data[0] * 0.1))  # manometer T
                self.grid_3.SetCellValue([0, 1], str(raw_mano_data[1] * 0.01))  # manometer P
                self.grid_3.SetCellValue([0, 2], str(raw_mano_data[2] * 0.01))  # manometer P20
                self.grid_3.SetCellValue([0, 3], str(raw_mano_data[3] * 0.01))  # manometer P20 avg

                # self.grid_1.SetCellValue([0, 0], str(raw_t_data[0] * 0.1))
                # self.grid_1.SetCellValue([0, 1], str(raw_t_data[1] * 0.1))
                # self.grid_1.SetCellValue([0, 2], str(raw_t_data[2] * 0.1))
                # self.grid_1.SetCellValue([1, 0], str(raw_t_data[3] * 0.1))
                # self.grid_1.SetCellValue([1, 1], str(raw_t_data[4] * 0.1))
                # self.grid_1.SetCellValue([1, 2], str(raw_t_data[5] * 0.1))
                # self.grid_1.SetCellValue([2, 0], str(raw_t_data[6] * 0.1))
                # self.grid_1.SetCellValue([2, 1], str(raw_t_data[7] * 0.1))
                # self.grid_1.SetCellValue([2, 2], str(raw_t_data[8] * 0.1))
                # self.grid_1.SetCellValue([3, 0], str(raw_t_data[9] * 0.1))
                # self.grid_1.SetCellValue([3, 1], str(raw_t_data[10] * 0.1))
                # self.grid_1.SetCellValue([3, 2], str(raw_t_data[11] * 0.1))
                # self.grid_1.SetCellValue([4, 0], str(raw_t_data[12] * 0.1))
                # self.grid_1.SetCellValue([4, 1], str(raw_t_data[13] * 0.1))
                # self.grid_1.SetCellValue([4, 2], str(raw_t_data[14] * 0.1))
                # self.grid_1.SetCellValue([5, 0], str(raw_t_data[15] * 0.1))
                # self.grid_1.SetCellValue([5, 1], str(raw_t_data[16] * 0.1))
                # self.grid_1.SetCellValue([5, 2], str(raw_t_data[17] * 0.1))
                for row in range(6):
                    for col in range(3):
                        self.grid_1.SetCellValue([row, col], str(raw_t_data[row * 3 + col] * 0.1))

                line_buf = line_default
                localtime = time.localtime(time.time())
                time_string = "{:04d}-{:02d}-{:02d} {:02d}:{:02d}:{:02d}".format(localtime.tm_year, localtime.tm_mon, localtime.tm_mday,
                                                                                 localtime.tm_hour, localtime.tm_min, localtime.tm_sec)
                line_buf['Time'] = time_string
                line_buf['Env_T'] = self.grid_2.GetCellValue(0, 0)
                line_buf['Env_H'] = self.grid_2.GetCellValue(0, 1)
                for row in range(6):
                    for col in range(3):
                        line_buf[var_names[3 + col + row * 3]] = self.grid_1.GetCellValue(row, col)
                        # line_buf[var_names[3 + col + row * 3]] = 0
                line_buf['Unit1_Mano_T'] = self.grid_3.GetCellValue(0, 0)
                line_buf['Unit1_Mano_P'] = self.grid_3.GetCellValue(0, 1)
                line_buf['Unit1_Mano_P20'] = self.grid_3.GetCellValue(0, 2)
                line_buf['Unit1_Mano_P20_avg'] = self.grid_3.GetCellValue(0, 3)
                writer.writerow(line_buf)
        except FileNotFoundError:
            self.frame_statusbar.SetStatusText('Error: please specify the data folder!', 0)
            self.stop_timer()
        except ModbusInvalidResponseError:
            self.frame_statusbar.SetStatusText('Error: please check Modbus Addr./RS485 Cable.', 0)
            self.stop_timer()
        except Exception as err:
            # self.label_4.SetLabelText("Status: ERROR")
            self.frame_statusbar.SetStatusText('Unknown error...', 0)
            self.stop_timer()
            raise err


# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp


if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
